/**
 * Curated list of car brands offered in the brand dropdown (značka). Free text
 * is still allowed via the "Iné" option, so this list is a convenience, not a
 * constraint — editing it is a one-line change. Sorted alphabetically.
 */
export const CAR_BRANDS = [
  "Alfa Romeo",
  "Audi",
  "BMW",
  "Chevrolet",
  "Citroën",
  "Dacia",
  "Fiat",
  "Ford",
  "Honda",
  "Hyundai",
  "Iveco",
  "Jaguar",
  "Jeep",
  "Kia",
  "Land Rover",
  "Lexus",
  "Mazda",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "Renault",
  "SEAT",
  "Smart",
  "Subaru",
  "Suzuki",
  "Škoda",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
] as const;
